# Generated by Django 2.0.7 on 2018-07-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairsubs', '0002_auto_20180705_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpair',
            name='first_lang',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='subpair',
            name='id_movie_imdb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subpair',
            name='second_lang',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
