version: '2'

services:
  nginx:
    image: nginx:latest
    container_name: ng01_2
    ports:
      - "8080:80"
    volumes:
      - .:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    container_name: dg01_2
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn example.wsgi -t 3600 -b 0.0.0.0:8000"
    depends_on:
      - db
    links:
      - redis
    volumes:
      - .:/src
    expose:
      - "8000"
    stdin_open: true
    tty: true

  db:
    image: postgres:latest
    container_name: ps01_2
    volumes:
      - data:/var/lib/postgres/data

  redis:
    image: redis:latest
    container_name: rd01_2
    ports:
     - '6379:6379'

  celery:
    build: .
    container_name: cl01_2
    working_dir: /src
    command: celery -A example worker
    volumes:
      - .:/src
    links:
      - db
      - redis
    ports:
      - "6900-7000:6900-7000"


volumes:
  data: {}

